# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci-test

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: build HiGHS
      run: |
        chmod +x ./build_highs.sh
        ./build_highs.sh
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install repo
      run: |
        pip install -e .[dev]
    - name: Lint with precommit
      run: |
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest
