name: tz-solve build webhook

on:
  push:
    branches:
      - main
    paths:
      - 'tz/osemosys/**'
      - 'pyproject.toml'
      - '.github/workflows/tz-solve-osemosys-build-webhook.yml'

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger webhook
      run: |
        curl -X POST -H "Content-Type: application/json" -d "{}" "${{ secrets.TZ_SOLVE_OSEMOSYS_BUILD_WEBHOOK }}"
